#ifndef MOTION_CONTROLLER_WITHPIC__VISIBILITY_CONTROL_H_
#define MOTION_CONTROLLER_WITHPIC__VISIBILITY_CONTROL_H_
#if defined _WIN32 || defined __CYGWIN__
  #ifdef __GNUC__
    #define MOTION_CONTROLLER_WITHPIC_EXPORT __attribute__ ((dllexport))
    #define MOTION_CONTROLLER_WITHPIC_IMPORT __attribute__ ((dllimport))
  #else
    #define MOTION_CONTROLLER_WITHPIC_EXPORT __declspec(dllexport)
    #define MOTION_CONTROLLER_WITHPIC_IMPORT __declspec(dllimport)
  #endif
  #ifdef MOTION_CONTROLLER_WITHPIC_BUILDING_LIBRARY
    #define MOTION_CONTROLLER_WITHPIC_PUBLIC MOTION_CONTROLLER_WITHPIC_EXPORT
  #else
    #define MOTION_CONTROLLER_WITHPIC_PUBLIC MOTION_CONTROLLER_WITHPIC_IMPORT
  #endif
  #define MOTION_CONTROLLER_WITHPIC_PUBLIC_TYPE MOTION_CONTROLLER_WITHPIC_PUBLIC
  #define MOTION_CONTROLLER_WITHPIC_LOCAL
#else
  #define MOTION_CONTROLLER_WITHPIC_EXPORT __attribute__ ((visibility("default")))
  #define MOTION_CONTROLLER_WITHPIC_IMPORT
  #if __GNUC__ >= 4
    #define MOTION_CONTROLLER_WITHPIC_PUBLIC __attribute__ ((visibility("default")))
    #define MOTION_CONTROLLER_WITHPIC_LOCAL  __attribute__ ((visibility("hidden")))
  #else
    #define MOTION_CONTROLLER_WITHPIC_PUBLIC
    #define MOTION_CONTROLLER_WITHPIC_LOCAL
  #endif
  #define MOTION_CONTROLLER_WITHPIC_PUBLIC_TYPE
#endif
#endif  // MOTION_CONTROLLER_WITHPIC__VISIBILITY_CONTROL_H_
// Generated 09-Jan-2025 15:54:38
 