camera:
  camera:
    ros__parameters:
        camera_name: camera                      # 'default': 'camera', 'description': 'camera unique name'
        serial_no: ''                            # 'default': "''", 'description': 'choose device by serial number'
        usb_port_id: ''                          # 'default': "''", 'description': 'choose device by usb port id'
        config_file: ''                          # 'default': "''", 'description': 'yaml config file'
        unite_imu_method: 0                      # 'default': "0", 'description': '[0-None, 1-copy, 2-linear_interpolation]'
        json_file_path: ''                       # 'default': "''", 'description': 'allows advanced configuration'
        log_level: info                          # 'default': 'info', 'description': 'debug log level [DEBUG|INFO|WARN|ERROR|FATAL]'
        output: screen                           # 'default': 'screen', 'description': 'pipe node output [screen|log]'
        depth_module.profile: 848x480x30         # 'default': '0,0,0', 'description': 'depth module profile'                           
        enable_depth: true                       # 'default': 'true', 'description': 'enable depth stream'
        rgb_camera.profile: 1280x720x30          # 'default': '0,0,0', 'description': 'color image width'
        enable_color: true                       # 'default': 'true', 'description': 'enable color stream'
        enable_infra1: false                     # 'default': 'false', 'description': 'enable infra1 stream'
        enable_infra2: false                     # 'default': 'false', 'description': 'enable infra2 stream'
        infra_rgb: false                         # 'default': 'false', 'description': 'enable infra2 stream'
        tracking_module.profile: 0x0x0           # 'default': '0,0,0', 'description': 'fisheye width'
        enable_fisheye1: true                    # 'default': 'true', 'description': 'enable fisheye1 stream'
        enable_fisheye2: true                    # 'default': 'true', 'description': 'enable fisheye2 stream'
        enable_confidence: true                  # 'default': 'true', 'description': 'enable depth stream'
        gyro_fps: 0                              # 'default': '0', 'description': "''"                           
        accel_fps: 0                             # 'default': '0', 'description': "''"                           
        enable_gyro: false                       # 'default': 'false', 'description': "''"                           
        enable_accel: false                      # 'default': 'false', 'description': "''"                           
        enable_pose: true                        # 'default': 'true', 'description': "''"                           
        pose_fps: 200                            # 'default': '200', 'description': "''"                           
        pointcloud.enable: false                 # 'default': 'false', 'description':    
        pointcloud.stream_filter: 2              # 'default': '2', 'description': 'texture stream for pointcloud'
        pointcloud.stream_index_filter: 0        # 'default': '0', 'description': 'texture stream index for pointcloud'
        enable_sync: false                       # 'default': 'false', 'description': "''"                           
        align_depth.enable: false                # 'default': 'false', 'description': "''"                           
        colorizer.enable: false                  # 'default': 'false', 'description': "''"
        clip_distance: -2.                       # 'default': '-2.', 'description': "''"                           
        linear_accel_cov: 0.01                   # 'default': '0.01', 'description': "''"                           
        initial_reset: false                     # 'default': 'false', 'description': "''"                           
        allow_no_texture_points: false           # 'default': 'false', 'description': "''"                           
        ordered_pc: false                        # 'default': 'false', 'description':   
        calib_odom_file: ''                      # 'default': "''", 'description': "''"
        topic_odom_in: ''                        # 'default': "''", 'description': 'topic for T265 wheel odometry'
        tf_publish_rate: 0.0                     # 'default': '0.0', 'description': 'Rate of publishing static_tf'
        diagnostics_period: 0.0                  # 'default': '0.0', 'description': 'Rate of publishing diagnostics. 0=Disabled'
        decimation_filter.enable: false          # 'default': 'false', 'description': 'Rate of publishing static_tf'
        rosbag_filename: ''                      # 'default': "''", 'description': 'A realsense bagfile to run from as a device'
        depth_module.exposure.1: 7500            # 'default': '7500', 'description': 'Initial value for hdr_merge filter'
        depth_module.gain.1: 16                  # 'default': '16', 'description': 'Initial value for hdr_merge filter'
        depth_module.exposure.2: 1               # 'default': '1', 'description': 'Initial value for hdr_merge filter'
        depth_module.gain.2: 16                  # 'default': '16', 'description': 'Initial value for hdr_merge filter'
        wait_for_device_timeout: -1.             # 'default': '-1.', 'description': 'Timeout for waiting for device to connect (Seconds)'
        reconnect_timeout: 6.                    # 'default': '6.', 'description': 'Timeout(seconds) between consequtive reconnection attempts'




# [launch]: All log files can be found below /home/car01/.ros/log/2023-08-30-19-33-12-941737-car01-NUC11-532375
# [INFO] [launch]: Default logging verbosity is set to INFO
# [INFO] [realsense2_camera_node-1]: process started with pid [532376]
# [realsense2_camera_node-1] [INFO] [1693395193.132442163] [camera.camera]: RealSense ROS v4.51.1
# [realsense2_camera_node-1] [INFO] [1693395193.132529049] [camera.camera]: Built with LibRealSense v2.53.1
# [realsense2_camera_node-1] [INFO] [1693395193.132540884] [camera.camera]: Running with LibRealSense v2.53.1
# [realsense2_camera_node-1] [INFO] [1693395193.148537184] [camera.camera]: Device with serial number 943222110283 was found.
# [realsense2_camera_node-1] 
# [realsense2_camera_node-1] [INFO] [1693395193.148617464] [camera.camera]: Device with physical ID 4-3-2 was found.
# [realsense2_camera_node-1] [INFO] [1693395193.148627343] [camera.camera]: Device with name Intel RealSense T265 was found.
# [realsense2_camera_node-1] [INFO] [1693395193.148835076] [camera.camera]: Device with port number 4-3 was found.
# [realsense2_camera_node-1] [INFO] [1693395193.148848836] [camera.camera]: Device USB type: 3.1
# [realsense2_camera_node-1] [INFO] [1693395193.155142686] [camera.camera]: getParameters...
# [realsense2_camera_node-1] [WARN] [1693395193.155360910] [camera.camera]: Device does not support advanced settings!
# [realsense2_camera_node-1] [INFO] [1693395193.155373846] [camera.camera]: Device Name: Intel RealSense T265
# [realsense2_camera_node-1] [INFO] [1693395193.155380390] [camera.camera]: Device Serial No: 943222110283
# [realsense2_camera_node-1] [INFO] [1693395193.155388917] [camera.camera]: Device physical port: 4-3-2
# [realsense2_camera_node-1] [INFO] [1693395193.155393644] [camera.camera]: Device FW version: 0.2.0.951
# [realsense2_camera_node-1] [INFO] [1693395193.155399457] [camera.camera]: Device Product ID: 0x0B37
# [realsense2_camera_node-1] [INFO] [1693395193.155404575] [camera.camera]: Sync Mode: Off
# [realsense2_camera_node-1] [WARN] [1693395193.155649807] [camera.camera]: Could not set param: tracking_module.frames_queue_size with 256 Range: [0, 32]: parameter 'tracking_module.frames_queue_size' could not be set: Parameter {tracking_module.frames_queue_size} doesn't comply with integer range.
# [realsense2_camera_node-1] [INFO] [1693395193.156234338] [camera.camera]: Set ROS param tracking_module.profile to default: 848x800x30
# [realsense2_camera_node-1] [INFO] [1693395193.156285911] [camera.camera]: Set ROS param gyro_fps to default: 200
# [realsense2_camera_node-1] [INFO] [1693395193.156315572] [camera.camera]: Set ROS param accel_fps to default: 62
# [realsense2_camera_node-1] [WARN] [1693395193.190999309] [camera.camera]: Could not set param: pointcloud.stream_index_filter with -1 Range: [-1, -2147483648]: parameter 'pointcloud.stream_index_filter' could not be set: Parameter {pointcloud.stream_index_filter} doesn't comply with integer range.
# [realsense2_camera_node-1] [INFO] [1693395193.191895252] [camera.camera]: Stopping Sensor: Tracking Module
# [realsense2_camera_node-1] [INFO] [1693395193.195625238] [camera.camera]: Starting Sensor: Tracking Module
# [realsense2_camera_node-1] [INFO] [1693395193.197898980] [camera.camera]: Open profile: stream_type: Fisheye(1), Format: Y8, Width: 848, Height: 800, FPS: 30
# [realsense2_camera_node-1] [INFO] [1693395193.197937077] [camera.camera]: Open profile: stream_type: Fisheye(2), Format: Y8, Width: 848, Height: 800, FPS: 30
# [realsense2_camera_node-1] [INFO] [1693395193.197946835] [camera.camera]: Open profile: stream_type: Pose(0)Format: 6DOF, FPS: 200
# [realsense2_camera_node-1] [INFO] [1693395193.241410690] [camera.camera]: RealSense Node Is Up!
# [realsense2_camera_node-1] [WARN] [1693395193.269602908] [camera.camera]: 
# ^C[WARNING] [launch]: user interrupted with ctrl-c (SIGINT)
# [realsense2_camera_node-1] [INFO] [1693395255.358210936] [rclcpp]: signal_handler(signum=2)
# [realsense2_camera_node-1] [INFO] [1693395255.452667820] [camera.camera]: Stop Sensor: Tracking Module
# [realsense2_camera_node-1] [INFO] [1693395255.937616080] [camera.camera]: Close Sensor. 
# [realsense2_camera_node-1] [INFO] [1693395255.937776529] [camera.camera]: Close Sensor - Done. 
# [INFO] [realsense2_camera_node-1]: process has finished cleanly [pid 532376]