#ifndef MOTION_CONTROLLER_WITHTD3__VISIBILITY_CONTROL_H_
#define MOTION_CONTROLLER_WITHTD3__VISIBILITY_CONTROL_H_
#if defined _WIN32 || defined __CYGWIN__
  #ifdef __GNUC__
    #define MOTION_CONTROLLER_WITHTD3_EXPORT __attribute__ ((dllexport))
    #define MOTION_CONTROLLER_WITHTD3_IMPORT __attribute__ ((dllimport))
  #else
    #define MOTION_CONTROLLER_WITHTD3_EXPORT __declspec(dllexport)
    #define MOTION_CONTROLLER_WITHTD3_IMPORT __declspec(dllimport)
  #endif
  #ifdef MOTION_CONTROLLER_WITHTD3_BUILDING_LIBRARY
    #define MOTION_CONTROLLER_WITHTD3_PUBLIC MOTION_CONTROLLER_WITHTD3_EXPORT
  #else
    #define MOTION_CONTROLLER_WITHTD3_PUBLIC MOTION_CONTROLLER_WITHTD3_IMPORT
  #endif
  #define MOTION_CONTROLLER_WITHTD3_PUBLIC_TYPE MOTION_CONTROLLER_WITHTD3_PUBLIC
  #define MOTION_CONTROLLER_WITHTD3_LOCAL
#else
  #define MOTION_CONTROLLER_WITHTD3_EXPORT __attribute__ ((visibility("default")))
  #define MOTION_CONTROLLER_WITHTD3_IMPORT
  #if __GNUC__ >= 4
    #define MOTION_CONTROLLER_WITHTD3_PUBLIC __attribute__ ((visibility("default")))
    #define MOTION_CONTROLLER_WITHTD3_LOCAL  __attribute__ ((visibility("hidden")))
  #else
    #define MOTION_CONTROLLER_WITHTD3_PUBLIC
    #define MOTION_CONTROLLER_WITHTD3_LOCAL
  #endif
  #define MOTION_CONTROLLER_WITHTD3_PUBLIC_TYPE
#endif
#endif  // MOTION_CONTROLLER_WITHTD3__VISIBILITY_CONTROL_H_
// Generated 04-Apr-2025 17:42:06
 