motor_can_node : # node name
  ros__parameters:
    CanSeries: "can3"
    wheel_radius: 0.065
    motor_ratio: 5.18
    Kp: 1.0
    Ki: 0.05
    Kd: 0.0
    IBound: 0.2
    dt: 0.001
    preTorque: 0.15
    filter_a1: 0.828
    filter_b0: 0.086
    filter_b1: 0.086
    K_motor: 0.0813
    maxTorque: 1.6
    minTorque: -1.6
