motion_controller_withPIC:
  ros__parameters:
    Weight_Y: 180.0
    Weight_Vy: 10.0
    Weight_Yaw: 40.0
    Weight_YawRate: 10.0
    Weight_df: 10.0
    Weight_dr: 25.0
    Weight_ddf: 10.0
    Weight_ddr: 40.0
    mpc_lbub: 0.047123
    tireBf: -10.824
    tireCf: 1.228
    tireMuf: 0.431
    tireBr: -10.215
    tireCr: 1.277
    tireMur: 0.399
    # tireBf: -14.824
    # tireCf: 1.238
    # tireMuf: 0.435
    # tireBr: -14.215
    # tireCr: 1.277
    # tireMur: 0.405
    # tireBf: -49.824
    # tireCf: 1.128
    # tireMuf: 0.431
    # tireBr: -40.215
    # tireCr: 1.177
    # tireMur: 0.399
    spdMax: 4.5
    spdMax1: 4.5
    angleMax: 0.7
    angleMaxMpc: 0.7
    ackermann: 1.0
    effortMax: 0.6
    steer_rate_dps: 0.0
    acc_rate_mps: 0.0
    drive_by_2: False
    FWS: True
    picActivationDAy: 0.18
    picActivationDomegaz: 0.00
    testWithDrive: True
    noControl: False
    isMpcN20Else10: True
    isSetSteeringDead: True
    vxAdd: 0.1
    t265offset: 0.0
    rLPF: False
    rFilterUpdateRate: 0.01