servo_rs485_node : # node name
  ros__parameters:
    left_min_position: 1640
    left_mid_position: 2047
    left_max_position: 2500
    right_min_position: 1625
    right_mid_position: 2047
    right_max_position: 2380
    baud_rate: 2000000
    device_name: /dev/servo

