servo_rs485_node : # node name
  ros__parameters:
    # left_min_position: 1480
    # left_mid_position: 2048
    # left_max_position: 2552
    # right_min_position: 1490
    # right_mid_position: 2048
    # right_max_position: 2570 +-490
    left_min_position_f: 1558
    left_mid_position_f: 2048
    left_max_position_f: 2538
    right_min_position_f: 1558
    right_mid_position_f: 2048
    right_max_position_f: 2538
    left_min_position_r: 1558
    left_mid_position_r: 2048
    left_max_position_r: 2538
    right_min_position_r: 1558
    right_mid_position_r: 2048
    right_max_position_r: 2538
    baud_rate: 2000000
    device_name: /dev/servo

