servo_rs485_node : # node name
  ros__parameters:
    left_min_position: 1480
    left_mid_position: 2048
    left_max_position: 2552
    right_min_position: 1490
    right_mid_position: 2048
    right_max_position: 2570
    baud_rate: 2000000
    device_name: /dev/servo

