<robot xmlns:xacro="http://wiki.ros.org/xacro">
    <!-- PI 值 -->
    <xacro:property name="PI" value="3.1416"/>
    <!-- 定义参数 -->
    <!-- 中心车体长宽高 -->
    <xacro:property name="base_central_height" value="0.083"/>
    <xacro:property name="base_central_length" value="0.345"/>
    <xacro:property name="base_central_width" value="0.2"/>
    <!-- 前车体长宽高 -->
    <xacro:property name="base_front_height" value="0.083"/>
    <xacro:property name="base_front_length" value="0.141"/>
    <xacro:property name="base_front_width" value="0.078"/>
    <!-- 后车体长宽高 -->
    <xacro:property name="base_back_height" value="0.083"/>
    <xacro:property name="base_back_length" value="0.141"/>
    <xacro:property name="base_back_width" value="0.078"/>
    <!-- 离地间距 -->
    <xacro:property name="base_to_plane" value="0.015"/>
    <!-- 车轮半径 宽度 到车体长度-->
    <xacro:property name="wheel_radius" value="0.065"/>
    <xacro:property name="wheel_length" value="0.070"/>
    <xacro:property name="wheel_to_base" value="0.096"/>
    <!--板到车体长度 前后 厚 左右 上下-->
    <xacro:property name="ban_to_base" value="0.122"/>
    <xacro:property name="ban_width" value="0.100"/>
    <xacro:property name="joint_move_right" value="0.225"/>
    <xacro:property name="joint_move_down" value="0.0"/>
    <!--支撑件到车体长度 前后 左右 上下-->
    <xacro:property name="supporter_width" value="0.030"/>
    <xacro:property name="distance_between" value="0.035"/>
    <xacro:property name="joint_to_base" value="0.120"/>
    <xacro:property name="joint_to_base_top" value="0.060"/>
    <!-- 定义颜色 -->
    <material name="gray">
        <color rgba="0.6 0.6 0.6 1" />
      </material>
    <material name="black">
        <color rgba="0.0 0.0 0.0 1" />
    </material>
    <material name="yellow">
        <color rgba="1.0 1.0 0.878 1" />
    </material>
    <!-- 定义 base_footprint -->
    <link name="base_footprint">
        <visual>
            <geometry>
                <sphere radius="0.001"/>
            </geometry>
        </visual>
    </link>

    <!-- 定义 base_link -->
    <link name="base_link">
        <visual>
            <!-- 形状 -->
            <geometry>
                <box size="${base_central_length} ${base_central_width} ${base_central_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="gray"/>
        </visual>
    </link>
    <joint name="baselink2basefootprint" type="fixed">
        <parent link="base_footprint"/>1/2
        <child link="base_link"/>
        <origin xyz="0.0 0.0 ${base_to_plane + base_central_height / 2}"/>
    </joint>
    <!-- 定义 base_front_link -->
    <link name="base_front_link">
        <visual>
            <!-- 形状 -->
            <geometry>
                <box size="${base_front_length} ${base_front_width} ${base_front_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="gray"/>
        </visual>
    </link>
    <joint name="basefrontlink2basecentrallink" type="fixed">
        <parent link="base_link"/>
        <child link="base_front_link"/>
        <origin xyz="${base_central_length / 2 + base_front_length / 2} 0.0 0.0"/>
    </joint>
    <!-- 定义 base_back_link -->
    <link name="base_back_link">base_front_height/2}"/>
        <visual>
            <!-- 形状 -->
            <geometry>
                <box size="${base_back_length} ${base_back_width} ${base_back_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="gray"/>
        </visual>
    </link>
    <joint name="basebacklink2basecentrallink" type="fixed">
        <parent link="base_link"/>
        <child link="base_back_link"/>
        <origin xyz="-${base_central_length / 2 + base_back_length / 2} 0.0 0.0"/>
    </joint>
    <!-- 定义 front_ban_link -->
    <link name="front_ban_link">
        <visual>
            <!-- 形状 -->
            <geometry>
                <mesh filename="package://car_urdf/meshes/ban.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <origin xyz="0 0 0" rpy="${PI / 2} 0 ${PI / 2}" />
            <material name="gray"/>
        </visual>
    </link>
    <joint name="frontbanlink2basefrontlink" type="fixed">
        <parent link="base_front_link"/>
        <child link="front_ban_link"/>
        <origin xyz="${ban_to_base-ban_width+base_front_length/2} -${joint_move_right} -${base_front_height/2}"/>
    </joint>
    <!-- 定义 back_ban_link -->
    <link name="back_ban_link">
        <visual>
            <!-- 形状 -->
            <geometry>
                <mesh filename="package://car_urdf/meshes/ban.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <origin xyz="0 0 0" rpy="${PI / 2} 0 -${PI / 2}" />
            <material name="gray"/>
        </visual>
    </link>
    <joint name="backbanlink2basebacklink" type="fixed">
        <parent link="base_back_link"/>
        <child link="back_ban_link"/>
        <origin xyz="-${ban_to_base-ban_width+base_back_length/2} ${joint_move_right} -${base_front_height/2}"/>
    </joint>
    <!-- 定义 supporter_link  前：-1 后：1 左：-1 右：1 -->
    <xacro:macro name="supporter_link_func" params="supporter_name link_name is_back is_right">
    <link name="${supporter_name}_supporter_link">
        <visual>
            <!-- 形状 -->
            <geometry>
                <mesh filename="package://car_urdf/meshes/supporter.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <origin xyz="0 0 0" rpy="${PI / 2} 0 ${(PI / 2)*(is_back / 2 - 1 / 2)+(PI / 2)*(is_back / 2 + 1 / 2)}" />
            <material name="yellow"/>
        </visual>
    </link>
    <joint name="${supporter_name}supporterlink2base${link_name}link" type="fixed">
        <parent link="base_${link_name}_link"/>
        <child link="${supporter_name}_supporter_link"/>
        <origin xyz="${(joint_to_base+base_front_length/2)*is_back*(-1)} ${(supporter_width*(is_back/2+is_right/2)*(is_back/2+is_right/2)+distance_between / 2)*(-1)*is_right} -${joint_to_base_top-base_front_height/2}"/>
    </joint>
    </xacro:macro>
    <xacro:supporter_link_func supporter_name="frontleft" link_name="front" is_back="-1" is_right="-1" />
    <xacro:supporter_link_func supporter_name="frontright" link_name="front" is_back="-1" is_right="1" />
    <xacro:supporter_link_func supporter_name="backleft" link_name="back" is_back="1" is_right="-1" />
    <xacro:supporter_link_func supporter_name="backright" link_name="back" is_back="1" is_right="1" />
    <!-- 车轮前转轴宏定义 -->
    <xacro:macro name="wheel_bar_func" params="bar_name is_left" >
        <link name="${bar_name}_bar">
            <visual>
                <geometry>
                    <sphere radius="0.01"/>
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <material name="black"/>
            </visual>
        </link>
        <joint name="${bar_name}2basefrontlink" type="continuous">
            <parent link="base_front_link"  />
            <child link="${bar_name}_bar" />
            <origin xyz="0.0 ${(base_front_width/2+wheel_length/2+wheel_to_base)*is_left} 0.0" rpy="0 0 0" />
            <axis xyz="0 0 1" />
        </joint>
    </xacro:macro>
    <xacro:wheel_bar_func bar_name="left" is_left="-1" />
    <xacro:wheel_bar_func bar_name="right" is_left="1" />
    <!-- 后车轮宏定义 -->
    <xacro:macro name="wheel_back_func" params="wheel_name  is_left" >
        <link name="${wheel_name}_back_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${PI / 2} 0 0" />
                <material name="black"/>
            </visual>
        </link>
        <joint name="${wheel_name}back2basebacklink" type="continuous">
            <parent link="base_back_link"  />
            <child link="${wheel_name}_back_wheel" />
            <origin xyz="0 ${(base_front_width/2+wheel_length/2+wheel_to_base)*is_left} 0.0" rpy="0 0 0" />
            <axis xyz="0 1 0" />
        </joint>
    </xacro:macro>
    <!-- 车轮宏调用 -->
    <xacro:wheel_back_func wheel_name="right" is_left="1" />
    <xacro:wheel_back_func wheel_name="left" is_left="-1" />
    <!-- 前车轮宏定义 -->
    <xacro:macro name="wheel_front_func" params="wheel_name" >
        <link name="${wheel_name}_front_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${PI / 2} 0 0" />
                <material name="black"/>
            </visual>
        </link>
        <joint name="${wheel_name}front2bar" type="continuous">
            <parent link="${wheel_name}_bar"  />
            <child link="${wheel_name}_front_wheel" />
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
            <axis xyz="0 1 0" />
        </joint>
    </xacro:macro>
    <!-- 车轮宏调用 -->
    <xacro:wheel_front_func wheel_name="right" />
    <xacro:wheel_front_func wheel_name="left"
     />
</robot>