#ifndef MOTION_CONTROLLER_CIRCLE_TEST__VISIBILITY_CONTROL_H_
#define MOTION_CONTROLLER_CIRCLE_TEST__VISIBILITY_CONTROL_H_
#if defined _WIN32 || defined __CYGWIN__
  #ifdef __GNUC__
    #define MOTION_CONTROLLER_CIRCLE_TEST_EXPORT __attribute__ ((dllexport))
    #define MOTION_CONTROLLER_CIRCLE_TEST_IMPORT __attribute__ ((dllimport))
  #else
    #define MOTION_CONTROLLER_CIRCLE_TEST_EXPORT __declspec(dllexport)
    #define MOTION_CONTROLLER_CIRCLE_TEST_IMPORT __declspec(dllimport)
  #endif
  #ifdef MOTION_CONTROLLER_CIRCLE_TEST_BUILDING_LIBRARY
    #define MOTION_CONTROLLER_CIRCLE_TEST_PUBLIC MOTION_CONTROLLER_CIRCLE_TEST_EXPORT
  #else
    #define MOTION_CONTROLLER_CIRCLE_TEST_PUBLIC MOTION_CONTROLLER_CIRCLE_TEST_IMPORT
  #endif
  #define MOTION_CONTROLLER_CIRCLE_TEST_PUBLIC_TYPE MOTION_CONTROLLER_CIRCLE_TEST_PUBLIC
  #define MOTION_CONTROLLER_CIRCLE_TEST_LOCAL
#else
  #define MOTION_CONTROLLER_CIRCLE_TEST_EXPORT __attribute__ ((visibility("default")))
  #define MOTION_CONTROLLER_CIRCLE_TEST_IMPORT
  #if __GNUC__ >= 4
    #define MOTION_CONTROLLER_CIRCLE_TEST_PUBLIC __attribute__ ((visibility("default")))
    #define MOTION_CONTROLLER_CIRCLE_TEST_LOCAL  __attribute__ ((visibility("hidden")))
  #else
    #define MOTION_CONTROLLER_CIRCLE_TEST_PUBLIC
    #define MOTION_CONTROLLER_CIRCLE_TEST_LOCAL
  #endif
  #define MOTION_CONTROLLER_CIRCLE_TEST_PUBLIC_TYPE
#endif
#endif  // MOTION_CONTROLLER_CIRCLE_TEST__VISIBILITY_CONTROL_H_
// Generated 19-Dec-2023 21:19:58
 